apps/gym/urls.py
from os import abort
from django.urls import path

# from django.contrib.auth import views as auth_views

from apps.gym.views import Logout, about, approve, becomemember, contact, delete\
    , home, service, signin, signup, trainer, trainerdetails, userprofil, update, predict,result

app_name = 'gym'

urlpatterns = [
    path('', home, name='home'),
    path('signup', signup, name='signup'),
    path('logout/', Logout, name='logout'),
    path('signin', signin, name='signin'),
    path('member', becomemember, name='member'),
    path('memberupdate/<int:pk>', update, name="memberupdate"),
    path('userprofil/<int:pk>', userprofil, name='userprofil'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('approve', approve, name='approve'),
    path('service', service, name='service'),
    path('contact', contact, name='contact'),
    path("about", about, name='about'),
    path('trainer',trainer,name='trainer'),
    path('trainerdetail/<int:pk>',trainerdetails,name="trainerdetail"),
    path('predict/',predict,name='predict'),
    path('predict/result',result,name='result'),
]

config/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.gym.urls')),
    path('reset_password/',
     auth_views.PasswordResetView.as_view(),
     name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(), 
        name="password_reset_done"),

    path('password/reset/confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'), 
        name="password_reset_complete"),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    

templates/pages/about.html
{% extends "base.html"%}

{% load static %}

{% block body_content %}

  <section class="abt-01">
      <div class="container">
          <div class="row">
              <div class="col-12">
                  <div class="wrapper">
                      <h2>About Us</h2>
                      <ul>
                          <a href = "{% url 'gym:home' %}">
                            <li>Home<i class="far fa-angle-double-right"></i></li>
                          </a>
                          {% comment %} <li>Home<i class="far fa-angle-double-right"></i></li> {% endcomment %}
                          <li>About Us</li>
                      </ul>
                  </div>
              </div>
          </div>
      </div>
  </section>

  <section class="about-us">
      <div class="container">

          <div class="row natur-row no-margin w-100">
              <div class="text-part col-md-6">
                  <h2>Welcome to <span>Smart Fitness</span></h2>
                  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis varius faucibus
                      ligula non congue. Suspendisse at pretium massa, sit amet
                      vulputate nibh. Nam posuere eros dolor. Donec vel arcu sagittis, pretium nisl </p>
                  <p> Cras faucibus laoreet nibh, sit amet tincidunt leo mollis in. Etiam eu mauris metus.
                      Nulla facilisi. Etiam vestibulum,
                      nisi et convallis elementum, leo orci aliquam metus, id posuere massa neque vitae
                      arcu.</p>

                  <p>Integer vulputate vehicula dolor a eleifend. Duis aliquam condimentum sapien,
                      eget tempor justo. Aenean porttitor nibh metus, sollicitudin egestas metus posuere et
                      . Fusce egestas volutpat metus, in sodales sem bibendum porta. Nunc hendrerit nunc sit
                      amet tellus posuere, at malesuada sem gravida. Integer maximus ultricies augue, at
                      dapibus elit bibendum consequat. Cras faucibus tellus eleifend, fermentum purus in,
                      dapibus sapien. Praesent nec ornare risus. Etiam iaculis, ligula vel gravida
                      vestibulum, urna justo posuere ante,
                      id pretium massa arcu sed mi. Nunc a sollicitudin sem. Duis tempus </p>
              </div>
              <div class="image-part col-md-6">
                  <img src="{% static 'images/abt-01.png' %}" alt="">
              </div>
          </div>
      </div>
  </section>


  <section class="bg-05">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="heading">
            <h2>Our Package</h2>
          </div>
        </div>
      </div>
      
      <table class="table table-hover ">
        <thead style="color:#000 ; font-weight: bold;">
          <tr>
            <th scope="col">SN</th>
            <th scope="col">NAME</th>
            <th scope="col">AMOUNT</th>
            <th scope="col">DURATION</th>
          </tr>
        </thead>
        
        <tbody >
          {% for plan in plans %}
          <tr style="color:#000;font-weight: bold; text-transform: uppercase;">
            <th scope="row">{{forloop.counter}}</th>
            <td>{{plan.name}}</td>
            <td>{{plan.amount}}</td>
            <td>{{plan.duration}}</td>
          </tr>
          {% endfor %}
          
        </tbody>
       
      </table>
    
    </div>



  <section class="bg-06">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="wrapper">
            <ul>
              <li>
                <i class="fal fa-play-circle"></i>
                <strong class="text-uppercase">Explore life fitness</strong>
                <a>Training Vide</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>

  {% endblock %}

templates/pages/approved.html
{% extends "base.html"%}
{%load crispy_forms_tags %} 

{% load static %}

{% block body_content %}
<br>

<h1 style="color: blue; text-align: center;" >you have following plan:</h1>
<br>


{% if user.is_authenticated %}

{% if info.is_approved %}
<p> </p>
<table class="table table-hover table-dark">
     <thead>
       <tr>
         <th scope="col">Name</th>
         <th scope="col">Plan Name</th>
         <th scope="col">Plan Amount</th>
         <th scope="col">InitialAmount</th>
         <th scope="col">DueAmount</th>
         <th scope="col">Status</th>

         <th scope="col">Delete</th>


       </tr>
     </thead>
     <tbody>
       <tr>
         <th scope="row">{{user.full_name}}</th>
         <td>{{plan.name}}</td>
         <td>{{plan.amount}}</td>
         <td>{{info.initialamount}}</td>
         <td>Rs:- {{due_amount}}</td>
         <td>{{info.status}}</td>

         <td class="d-flex justify-content-between">
          <a href="{% url 'gym:delete' info.id %}"><i class="text-danger">delete</i></a>
          </td>




        
       </tr>
     </tbody>
   </table>

{% else %}
<table class="table table-hover table-dark">
  <thead>
    <tr>
      <th scope="col">Name</th>
      
      
      
      <th scope="col">Status</th>
      <th scope="col">Action</th>


    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">{{user.full_name}}</th>
     
      <td>{{info.status}}</td>
      <td class="d-flex justify-content-between">
        <a href="{% url 'gym:memberupdate' info.pk %}"><i class="text-danger">Update</i></a>
        
       <a href="{% url 'gym:delete' info.id %}"><i class="text-danger">delete</i></a>
       </td>




     
    </tr>
  </tbody>
</table>

{% endif %}




{% endif %}
<br>
{% endblock %}

templates/pages/becomemember.html
{% extends "base.html"%}
{%load crispy_forms_tags %}

{% load static %}

{% block body_content %}



<section class="ftco-section">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-md-6 text-center mb-5">
				<h2 class="heading-section">Gym Membership</h2>
			</div>
		</div>
		<div class="row justify-content-center">
			<div class="col-md-12 col-lg-10">
				<div class="wrap d-md-flex">
					<div class="text-wrap p-4 p-lg-5 text-center d-flex align-items-center order-md-last">
						<div class="text w-100">
							<h2>Welcome to Membership</h2>
							
							<a href="{% url 'gym:approve' %}" class="btn btn-white btn-outline-white">View
								Membership</a>
						</div>
					</div>
					<div class="login-wrap p-4 p-lg-5">
						<div class="d-flex">
							<div class="w-100">
								<h3 class="mb-4">Membership</h3>
							</div>
							<div class="w-100">
								<p class="social-media d-flex justify-content-end">
									<a href="#"
										class="social-icon d-flex align-items-center justify-content-center"><span
											class="fa fa-facebook"></span></a>
									<a href="#"
										class="social-icon d-flex align-items-center justify-content-center"><span
											class="fa fa-twitter"></span></a>
								</p>
							</div>
						</div>
						<form action="#" class="signin-form" method="post">
							{% csrf_token %}

							<div class="form-group mb-3 label">
								{{ form|crispy }}



							</div>

							<div class="form-group">
								<button type="submit" class="form-control btn btn-primary submit px-3">Become a
									Member</button>
							</div>

						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/pages/contact-us.html

{% extends "base.html"%}
{%load crispy_forms_tags %} 

{% load static %}

{% block body_content %}

  <section class="abt-01">
      <div class="container">
          <div class="row">
              <div class="col-12">
                  <div class="wrapper">
                      <h2>Contact Us</h2>
                      <ul>
                          <li>Home<i class="far fa-angle-double-right"></i></li>
                          <li>Contact Us</li>
                      </ul>
                  </div>
              </div>
          </div>
      </div>
  </section>
  <div style="margin-top:0px;" class="row no-margin">
    <iframe style="width:100%" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3534.013871478678!2d85.34749421410623!3d27.655042534397534!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x39eb1756a05a3d67%3A0x1088014f109e8b07!2sImadol%20Tempo%20Park!5e0!3m2!1sen!2snp!4v1653656014246!5m2!1sen!2snp" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>

 

  <section class="my-pla">
      <div class="container">
          <div class="row">
              <div class="col-12">
                  <div class="heading">
                      <h2>Get In Touch</h2>
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
                          tempor incididunt</p>
                  </div>
              </div>
          </div>
<form action="" method="POST">
          <div class="row">
              <div class="col-lg-6 col-12">
                  <div class="form-group">
                      
                      {% csrf_token %} 
                      {{ form|crispy }}

                  </div>
                  <div class="form-group">
                    <button type="submit" class="form-control btn btn-primary submit px-3">Submit</button>
                </div>
              </div>

             

             

             

              
          </div>
        </form>
      </div>
  </section>

  {% endblock %}

templates/pages/index.html
{% extends "base.html"%}


{% load static %}

{% block body_content %}

  <style>
    .a{
		max-width: 200px;
		max-height:300px;
		margin: 0 auto
		
	}
    .container1{
      display: flex;
      
    }
  </style>
<section class="slider">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
          {% for object in car %}
          <div class="carousel-item {% if forloop.counter0 == 0 %} active {% endif %}">
          <img style="height: 600px;" class="d-block w-100" src="{{object.image.url}}">
          </div>
          
          {% endfor %}
      </div>
  </div>
  
          
          
          




  <section class="bg-01">
    <div class="wrapper d-flex">
      <div class="left-side">
       <h2>32%
         <span>Discount</span>
       </h2>
       <a href="#playnow">Play Now</a>
      </div>
      <div class="right-side d-flex">
        <div class="container">
          <div class="row">
            <div class="col-md-4 col-sm-6 col-xs-12">
              <div class="content">
                <h3>Beginnner</h3>
                <span>$20</span>
                <p>f you need a bit of inspiration check out or
                   gym sample plans for fitness centers, corporate fitness,
                    gyms, health clubs, as well as martial arts studios, gymnastics schools, 
                  and a number of other athletics businesses.</p>
                  <a>Read More<i class="fal fa-arrow-right"></i></a>
              </div>
            </div>
            <div class="col-md-4 col-sm-6 col-xs-12">
              <div class="content">
                <h3>Advanced</h3>
                <span>$30</span>
                <p>If you’re looking to develop a more modern business plan,
                   we recommend you try LivePlan. It contains the same
                    templates and information you see here, but with additional
                   guidance to help you develop the perfect plan.</p>
                <a>Read More<i class="fal fa-arrow-right"></i></a>
              </div>
            </div>
            <div class="col-md-4 col-sm-6 col-xs-12">
              <div class="content">
                <h3>Warrior</h3>
                <span>$40</span>
                <p>At Corporate Fitness, we tie worker productivity directly
                   to the health care issue. We believe that traditional approaches
                    to the current health care crisis are misdirected. These traditional 
                    efforts are what we call reactive–that is, they wait until after the worker
                     has been stricken with illness or injury,
                   and then pay for the necessary treatments.</p>
                <a>Read More<i class="fal fa-arrow-right"></i></a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <div class="container" style="margin-top:60px">
    
    <br><br><br>
    <div class="row">
        <div class="col-sm-3 text-center mydivstyle">
            <h2 style="color: blue;">{{e1}}</h2>
            <h4 style="color:black;">Enquiry</h4>
            <hr class="rounded">
        </div>
        <div class="col-sm-3 text-center mydivstyle">
            <h2 style="color: blue;">{{p1}}</h2>
            <h4 style="color:black;">Plan</h4>
            <hr class="rounded">
        </div>
        <div class="col-sm-3 text-center mydivstyle">
            <h2 style="color: blue;">{{eq1}}</h2>
            <h4 style="color:black;">Equipment</h4>
            <hr class="rounded">
        </div>
        <div class="col-sm-3 text-center mydivstyle">
            <h2 style="color: blue;">{{m1}}</h2>
            <h4 style="color:black;">Member</h4>
            <hr class="rounded">
        </div>
    </div>
</div>

  <section class="bg-03">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="heading">
            <h2>Our Populer Classes</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. 
              Unde, id eos? Eaque, distinctio nisi. Cum dolorem, obcaecati 
              eos officiis, voluptate deserunt quasi quibusdam reprehenderit 
              voluptatum eius commodi illo exercitationem asperiores.</p>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-3 col-sm-4 col-xs-6">
          <div class="wrapper">
            <div class="image">
              <img src="{% static 'images/class/1.jpg' %}">
              <div class="inner-link">
                <a>Duration-20 Minuteus</a>
              </div>
            </div>
            <div class="content">
              <h4>BodyBuildind Program</h4>
              <span>Coach Shame Demo</span>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. 
                Autem mollitia labore perferendis officia dolorum in tempore</p>
                <a>Read More</a>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-4 col-xs-6">
          <div class="wrapper">
            <div class="image">
              <img src="{% static 'images/class/2.jpg' %}">
              <div class="inner-link">
                <a>Duration-20 Minuteus</a>
              </div>
            </div>
            <div class="content">
              <h4>BodyBuildind Program</h4>
              <span>Coach Shame Demo</span>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Autem mollitia labore perferendis officia dolorum in tempore</p>
              <a>Read More</a>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-4 col-xs-6">
          <div class="wrapper">
            <div class="image">
              <img src="{% static 'images/class/3.jpg' %}">
              <div class="inner-link">
                <a>Duration-20 Minuteus</a>
              </div>
            </div>
            <div class="content">
              <h4>BodyBuildind Program</h4>
              <span>Coach Shame Demo</span>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Autem mollitia labore perferendis officia dolorum in tempore</p>
              <a>Read More</a>
            </div>
          </div>
        </div>
        <div class="col-md-3 col-sm-4 col-xs-6">
          <div class="wrapper">
            <div class="image">
              <img src="{% static 'images/class/4.jpg' %}">
              <div class="inner-link">
                <a>Duration-20 Minuteus</a>
              </div>
            </div>
            <div class="content">
              <h4>BodyBuildind Program</h4>
              <span>Coach Shame Demo</span>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Autem mollitia labore perferendis officia dolorum in tempore</p>
              <a>Read More</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="bg-04" id="playnow">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="heading">
            <h2>Our Trainer</h2>
          </div>
        </div>
      </div>
     
      <div class="container1">
        {% for trainer in trainers %} 
        <div class="col-md-3 col-sm-6 col-xs-6">
          <div class="team-wrapper">
            <div class="a">
              <img  src="{{trainer.user.image.url}}">
            </div>
            
            <div class="content">
              <a href="{% url 'gym:trainerdetail' trainer.id %}"><h4 style="text-transform: uppercase">{{ trainer.user.full_name }}</h4></a>
              <span style="text-transform: uppercase">{{trainer.department}}</span>
            
            </div>
          </div>
        </div>
      {% endfor %} 

      
      
      </div>
    
    </div>
    </div>
  </section>

 
  <section class="bg-06">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="wrapper">
            <ul>
              <li>
                <i class="fal fa-play-circle"></i>
                <strong class="text-uppercase">Explore life fitness</strong>
                <a>Training Vide</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="bg-07">
    <div class="container">
      <div class="row">
        <div class="col-12">
          <div class="heading">
            <h2>Latest News</h2>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4 col-sm-6 col-xs-12">
          <div class="wrapper">
            <div class="image">
              <img src="{% static 'images/blog/1.jpg' %}">
              <div class="inner-link">
                <a>Sports</a>
              </div>
            </div>
            <div class="content">
              <h4>Body Building Program</h4>
              <ul>
                <li><i class="far fa-user"></i> By Admin</li>
                <li><i class="fal fa-calendar-alt"></i>9-28-2020</li>
              </ul>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Autem mollitia labore perferendis officia dolorum in tempore</p>
              <a>Read More</a>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-sm-6 col-xs-12">
          <div class="wrapper">
            <div class="image">
              <img src="{% static 'images/blog/2.jpg' %}">
              <div class="inner-link">
                <a>Sports</a>
              </div>
            </div>
            <div class="content">
              <h4>Body Building Program</h4>
              <ul>
                <li><i class="far fa-user"></i> By Admin</li>
                <li><i class="fal fa-calendar-alt"></i>9-28-2020</li>
              </ul>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Autem mollitia labore perferendis officia dolorum in tempore</p>
              <a>Read More</a>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-sm-6 col-xs-12">
          <div class="wrapper">
            <div class="image">
              <img src="{% static 'images/blog/3.jpg' %}">
              <div class="inner-link">
                <a>Sports</a>
              </div>
            </div>
            <div class="content">
              <h4>Body Building Program</h4>
              <ul>
                <li><i class="far fa-user"></i> By Admin</li>
                <li><i class="fal fa-calendar-alt"></i>9-28-2020</li>
              </ul>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.
                Autem mollitia labore perferendis officia dolorum in tempore</p>
              <a>Read More</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  
{% endblock %}



templates/pages/passwordreset.html
{% extends "base.html"%}
{%load crispy_forms_tags %} 

{% load static %}

{% block body_content %}


	
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Login #07</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-12 col-lg-10">
					<div class="wrap d-md-flex">
						<div class="text-wrap p-4 p-lg-5 text-center d-flex align-items-center order-md-last">
							<div class="text w-100">
								<h2>Welcome to login</h2>
								<p>Don't have an account?</p>
								<a href="{% url 'gym:signup' %}" class="btn btn-white btn-outline-white">Sign Up</a>
							</div>
			      </div>
						<div class="login-wrap p-4 p-lg-5">
			      	<div class="d-flex">
			      		<div class="w-100">
			      			<h3 class="mb-4">Sign In</h3>
			      		</div>
								<div class="w-100">
									<p class="social-media d-flex justify-content-end">
										<a href="#" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-facebook"></span></a>
										<a href="#" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-twitter"></span></a>
									</p>
								</div>
			      	</div>
							<form action="#" class="signin-form" method="post">
								 {% csrf_token %} 

			      		<div class="form-group mb-3 label" >
                            {{ form|crispy }}
			      			
			      		</div>
		           
		            <div class="form-group">
		            	<button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
		            </div>
		            <div class="form-group d-md-flex">
		            	<div class="w-50 text-left">
			            	<label class="checkbox-wrap checkbox-primary mb-0">Remember Me
									  <input type="checkbox" checked>
									  <span class="checkmark"></span>
										</label>
									</div>
									<div class="w-50 text-md-right">
										<a href="#">Forgot Password</a>
									</div>
		            </div>
		          </form>
		        </div>
		      </div>
				</div>
			</div>
		</div>
	</section>
	{% endblock %}

templates/pages/signin.html
{% extends "base.html"%}
{%load crispy_forms_tags %} 

{% load static %}

{% block body_content %}


	
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">Login #07</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-12 col-lg-10">
					<div class="wrap d-md-flex">
						<div class="text-wrap p-4 p-lg-5 text-center d-flex align-items-center order-md-last">
							<div class="text w-100">
								<h2>Welcome to login</h2>
								<p>Don't have an account?</p>
								<a href="{% url 'gym:signup' %}" class="btn btn-white btn-outline-white">Sign Up</a>
							</div>
			      </div>
						<div class="login-wrap p-4 p-lg-5">
			      	<div class="d-flex">
			      		<div class="w-100">
			      			<h3 class="mb-4">Sign In</h3>
			      		</div>
								<div class="w-100">
									<p class="social-media d-flex justify-content-end">
										<a href="#" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-facebook"></span></a>
										<a href="#" class="social-icon d-flex align-items-center justify-content-center"><span class="fa fa-twitter"></span></a>
									</p>
								</div>
			      	</div>
							<form action="#" class="signin-form" method="post">
								 {% csrf_token %} 

			      		<div class="form-group mb-3 label" >
                            {{ form|crispy }}
			      			
			      		</div>
		           
		            <div class="form-group">
		            	<button type="submit" class="form-control btn btn-primary submit px-3">Sign In</button>
		            </div>
		            <div class="form-group d-md-flex">
		            	<div class="w-50 text-left">
			            	<label class="checkbox-wrap checkbox-primary mb-0">Remember Me
									  <input type="checkbox" checked>
									  <span class="checkmark"></span>
										</label>
									</div>
									<div class="w-50 text-md-right">
										<a href="reset_password">Forgot Password</a>
									</div>
		            </div>
		          </form>
		        </div>
		      </div>
				</div>
			</div>
		</div>
	</section>
	{% endblock %}

templates/pages/trainer.html
{% extends "base.html"%}
{%load crispy_forms_tags %} 

{% load static %}

{% block body_content %}
<br>

<h1 style="color: blue; text-align: center;" >you have following plan:</h1>
<br>





<table id="example" class="table table-hover" >
     <thead>
       <tr>
        <th scope="col">SN</th>
         <th scope="col">Name</th>
         <th scope="col">Date_of_birth</th>
         <th scope="col">Gender</th>
         <th scope="col">Trainer</th>
         <th scope="col">plan</th>
         <th scope="col">joindate</th>
         <th scope="col">expiredate</th>
         


       </tr>
     </thead>
     <tbody>
      
  
        {% for info in infos %}
        {% if info.is_approved %}
        
        
        


       <tr>
        <th scope="row">{{forloop.counter}}</th>
         <th scope="row">{{info.user.full_name}}</th>
         
         <td>{{info.date_of_birth}}</td>
         <td>{{info.gender}}</td>
         <td>{{info.trainer}}</td>
         
         <td>{{info.plan}}</td>
         
         
         

         <td>{{info.joindate}}</td>
         <td>{{info.expiredate}}</td>
        

        




        
       </tr>
     </tbody>
     {% endif %}
   
   {% endfor %}
   


   </table>
   {% endblock %}

templates/pages/trainerdetail.html
{% extends "base.html"%}
{%load crispy_forms_tags %} 

{% load static %}

{% block body_content %}



<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>

<br>
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<a class="btn btn-warning" href="{% url 'gym:home' %}"> &#8592; Back to Profile</a>
			<hr>
			<h3 style="text-align: center">Account Settings</h3>
			<hr>
            {% for trainerdetail in trainerdetails %}
			<img class="profile-pic" src="{{trainerdetail.user.image.url}}" >
           
		
		</div>
	</div>
   
	<div class="col-md-9">
        <h3 style="text-align: center;">Trainer Details</h3>
		<div class="card card-body" style="font-weight: bold; margin-top: 100px;text-transform: uppercase;">
            Name:- {{trainerdetail.user.full_name }}
            <br>
            Email:- {{trainerdetail.user.email }}
            <br>
            Address:- {{trainerdetail.user.address }}
            <br>
            Department:-{{trainerdetail.department }}
            <br>
            Number:- {{trainerdetail.user.number }}






			
			
            
		</div>
	</div>
</div>
{% endfor  %}



{% endblock %}

templates/pages/userprofil.html
{% extends "base.html"%}
{%load crispy_forms_tags %} 

{% load static %}

{% block body_content %}



<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>

<br>
<div class="row">
	<div class="col-md-3">
		<div class="card card-body">
			<a class="btn btn-warning" href="{% url 'gym:home' %}"> &#8592; Back to Profile</a>
			<hr>
			<h3 style="text-align: center">Account Settings</h3>
			<hr>
			<img class="profile-pic" src="{{user.image.url}}" >
		
		</div>
	</div>
	<div class="col-md-9">
		<div class="card card-body">
			
			<form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
			
				{{ form|crispy }}


		
			<input class="btn btn-primary" type="submit" value="Update" name="Update Information">
			</form>
		</div>
	</div>
</div>



{% endblock %}