apps/gym/urls.py
from os import abort
from django.urls import path

# from django.contrib.auth import views as auth_views

from apps.gym.views import Logout, about, approve, becomemember, contact, delete\
    , home, service, signin, signup, trainer, trainerdetails, userprofil, update, predict,result

app_name = 'gym'

urlpatterns = [
    path('', home, name='home'),
    path('signup', signup, name='signup'),
    path('logout/', Logout, name='logout'),
    path('signin', signin, name='signin'),
    path('member', becomemember, name='member'),
    path('memberupdate/<int:pk>', update, name="memberupdate"),
    path('userprofil/<int:pk>', userprofil, name='userprofil'),
    path('delete/<int:pk>/', delete, name='delete'),
    path('approve', approve, name='approve'),
    path('service', service, name='service'),
    path('contact', contact, name='contact'),
    path("about", about, name='about'),
    path('trainer',trainer,name='trainer'),
    path('trainerdetail/<int:pk>',trainerdetails,name="trainerdetail"),
    path('predict/',predict,name='predict'),
    path('predict/result',result,name='result'),
]

config/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.gym.urls')),
    path('reset_password/',
     auth_views.PasswordResetView.as_view(),
     name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(), 
        name="password_reset_done"),

    path('password/reset/confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_done.html'), 
        name="password_reset_complete"),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT,
    )
    

templates/includes/footer.html
{% load static %}
<footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-3 col-md-3 col-sm-6 col-6">
          <div class="footer-content">
            <img src="{% static 'logo.png' %}" alt="">
            
            <ul>
              <li><i class="fab fa-facebook-f"></i></li>
              <li><i class="fab fa-twitter"></i></li>
              <li><i class="fab fa-google"></i></li>
              <li><i class="fab fa-skype"></i></li>
            </ul>
          </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-6">
          <div class="footer-content">
            <h2>Quick Links</h2>
            <ol>
              <li><a href="{% url 'gym:home' %}"><i class="fal fa-angle-double-right"></i>Home</a></li>
             
            </ol>
          </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-6">
          <div class="footer-content">
            <h2>Classes</h2>
            <ol>
              
              <li><a href="{% url 'gym:contact' %}"><i class="fal fa-angle-double-right"></i>Contact Us</a></li>
            </ol>
          </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-6 col-6">
         
        </div>
      </div>
    </div>
    <div class="copy-right">
      <div class="container">
        <div class="copy-right-card">
          <p>© 2022 <a href="https://www.facebook.com/missionghimirey/">Mission ghimire.</a> All Rights Reserved | Privacy Policy</p>
        </div>
      </div>
    </div>
  </footer>

templates/includes/header.html
{% load static %}

<header>
    <div class="main-nav">
        <div class="container">
            <div class="row">

                <div class="logo">
                    <img src="{% static 'logo.png' %}">
                </div>
                <div class="my-nav">
                    <div class="menu">
                        <ul>
                            <li>
                                <a href="{% url 'gym:home' %}">Home</a>
                            </li>
                            <li>
                                <a href="{% url 'gym:about' %}">About Us</a>
                            </li>
                            <li>
                                <a href="{% url 'gym:predict' %}">Services</a>
                            </li>
                            {% if user.is_authenticated %}
                            {% if user.is_trainer %}
                            <li>
                                <a href="{% url 'gym:trainer' %}">Trainer</a>
                            </li>
                            {% else %}
                            <li>
                                <a href="{% url 'gym:member' %}">Member</a>
                            </li>
                            {% endif %}
                            {% endif %}


                            <li>
                                <a href="{% url 'gym:contact' %}">Contact Us</a>
                            </li>
                           

                        </ul>
                    </div>
                        <div class= "rrr">
                        <ul>
                        <li>
                            {% if user.is_authenticated %}

                            <a href="{% url 'gym:userprofil' user.id  %}" style="color:#000; font-weight: bold;">{{user.username}}</a>
                            <a href="{% url 'gym:logout' %}" style="color:#000;font-weight: bold;">Logout</a>
                            {% else %}
                            <a href="{% url 'gym:signin' %}"style="color:#000; font-weight: bold;">Login</a>

                            {% endif %}
                           

                        </li>
                    </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>